services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: salary_payment
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgressql/data # mount data volume
      - ./resource:/docker-entrypoint-initdb.d # mount entry folder

volumes:
  pgdata:
