version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: salary_payment
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: securepass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgressql/data
      - ./resource/db:/docker-entrypoint-initdb.d

volumes:
  pgdata:

